### PR TITLE
Fix editor crashes

### LINKED ISSUE #76: Creating a kotlin script in the editor crashes the editor
Currently the editor crashes when we create a kotlin script in it.
Cause: We added a failing condition for debug builds if a class could not be found:
```cpp
KtClass* GDKotlin::find_class(const StringName& p_script_path) {
#ifdef DEBUG_ENABLED
    //FIXME: this crashes the editor when creating a kotlin script through the godot editor. Cause: this function gets called for the newly created script but of course it's not compiled yet as it was just added now...
    JVM_ERR_FAIL_COND_V_MSG(!classes.has(p_script_path), nullptr,
                   vformat("Failed to find class for path: %s", p_script_path));
#endif
    return classes[p_script_path];
}
```

### LINKED ISSUE #81: Non project kotlin files crashes editor
If you have kotlin files (`kt`extension) which do not belong to the project itself in the project dirs, the editor crashes.
For example if you have a custom gradle plugin inside the main project dir, which is of course not built into the final  `main.jar` the editor crashes as it cannot find those classes in the `main.jar`.
I suspect the issue here is mainly that godot sees the kotlin files and tries to get script specific informations from them as it sees them as script resources.

### PR DESCRIPTION
**Pull request by chippmann**
This resolves #76 and resolves #81

### CODE REVIEW

File: src/gd_kotlin.cpp [hunk 1]
```diff
@@ -393,9 +393,9 @@ void GDKotlin::unregister_classes(jni::Env& p_env, jni::JObjectArray p_classes)
 
 KtClass* GDKotlin::find_class(const StringName& p_script_path) {
 #ifdef DEBUG_ENABLED
-    //FIXME: https://github.com/utopia-rise/godot-jvm/issues/76
-    JVM_ERR_FAIL_COND_V_MSG(!classes.has(p_script_path), nullptr,
-                   vformat("Failed to find class for path: %s", p_script_path));
+    if (!classes.has(p_script_path)) {
```
Comment (piiertho) [inline src/gd_kotlin.cpp:396]: I would at least make a print verbose here or even a print WARN.

Comment (chippmann) [reply src/gd_kotlin.cpp:396]: Not sure about that. Because this would print that message or warning for each kt class which is not registered in godot.
Which leads to hundret's of prints for bigger projects.

Comment (chippmann) [reply src/gd_kotlin.cpp:396]: This would clutter up the output in such a great way that it renders it unusable (if we use warnings) and mostly unusable for verbose logs in general

Comment (piiertho) [reply src/gd_kotlin.cpp:396]: True, anyway I don't have strong opinion, we'll see if we need it later for debugging.

**Review by piiertho — APPROVED** [review]

**Review by raniejade — APPROVED** [review]

File: src/gd_kotlin.cpp (hunk 1 above)
Comment (chippmann) [reply src/gd_kotlin.cpp:396]: :+1:
